config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batman-vs-superman' => 'pages#batman_vs_superman'

  post 'pages/save_voto'

  root 'pages#batman-vs-superman'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  	@tiempo = 300
  	render layout: "bootstrap"
  end

  def page2
  	render layout: "bootstrap"
  end

  def page3
  	render layout: "bootstrap"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  	@heroe = "batman"
  end

  def superman
  	@heroe = "superman"
  end

  def batman_vs_superman
  end

  def save_voto
  	@email = params[:txt_email]
  	@voto = Voto.new(heroe: @heroe, email: @email)
  	if @voto.save
  		response = "Se ha guardado los datos correctamente"
  		redirect_to controller: 'pages', action: 'batman-vs-superman', response: response
  	else
  		response = "Ocurrió un error al intentar guardar"  		
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et consequatur aliquam est, accusamus, perspiciatis enim quam in optio illum officia dolorum nihil aut quos minima similique explicabo sint obcaecati. Ratione?</p>
<h2 id="cuenta"><%= @tiempo %></h2>

<script>
	var tiempo = <%= @tiempo %>
	setInterval(function(){ 		
		$("#cuenta").text(tiempo);
		tiempo = tiempo-1
	}, 1000);
</script>

app/views/experiments/page2.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est, explicabo, dolor quam sequi porro doloribus reiciendis. Facere laborum sunt saepe ullam, optio inventore, deleniti voluptatibus quis eaque quibusdam voluptatem assumenda.</p>

app/views/experiments/page3.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit, mollitia neque aut, maiores exercitationem consectetur fugiat excepturi! Ipsa, cupiditate molestiae ipsam quibusdam officiis omnis doloribus molestias vitae quidem deserunt porro.</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= asset_path experiments_page1_path %>">Page 1</a></li>
        <li><a href="<%= asset_path experiments_page2_path %>">Page 2</a></li>
        <li><a href="<%= asset_path experiments_page3_path %>" data-turbolinks="false">Page 3</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boostrap Experiments</title>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %> <%= params[:action] %>">
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/pages/batman-vs-superman.html.erb
<div class="container-fluid">
	<div class="row big">
		<a href="<%= asset_path pages_batman_path %>">
			<div class="col-md-6 text-center big" id="batman">				
					<h1>I am Batman</h1>			
			</div>
		</a>
		<a href="<%= asset_path pages_batman_path %>">
			<div class="col-md-6 text-center big" id="superman">
				<h1>This looks like a job for Superman</h1>			
			</div>
		</a>
	</div>
	<% if params[:response].present?  %>
	<div class="alert alert-success alert-dismissible fade in" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
		<%= params[:response] %>
	</div>
	<% end  %>
</div>
<script>
	$("#batman").backstretch("<%= asset_path 'bg_batman.jpg' %>");
	$("#superman").backstretch("<%= asset_path 'bg_superman.jpg' %>");
</script>

app/views/pages/batman.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1>I am Batman</h1>		
		</div>
	</div><br><br><br><br><br>
	<div class="row">
		<div class="col-md-offset-4 col-md-4">
			<form class="form" method="post" action="<%= pages_save_voto_path %>">
				<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
			  <div class="form-group">
			    <label for="txt_email">Ingrese su Email</label>
			    <input type="email" class="form-control" id="txt_email" name="txt_email" placeholder="Email">
			  </div>
			  <button type="submit" class="btn btn-primary">Enviar Voto</button>
			</form>
		</div>
	</div>
</div>
<script>
	$.backstretch("<%= asset_path 'bg_batman.jpg' %>");
</script>

app/views/pages/superman.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1>This looks like a job for Superman</h1>			
		</div>
	</div>
</div>
<script>
	$.backstretch("<%= asset_path 'bg_superman.jpg' %>");
</script>